name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Adjust to your main branch name

permissions:
  id-token: write
  contents: read
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/1003608403675/locations/global/workloadIdentityPools/github-actions/providers/github-provider
          service_account: medical-admin-portal@unifycare-424906.iam.gserviceaccount.com
    
      - name: Build Docker image
        run: |
          # Use the correct repository URL for GCR or Artifact Registry
          docker build -t us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/deploytest .

      - name: Push Docker image
        run: |
          docker push us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/deploytest
          
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-node-app \
            --image gcr.io/${{ secrets.GCP_TEST_PROJECT_ID }}/my-node-app
            --set-env-vars ENV=dev
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
