name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v3
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_TEST_PROJECT_ID }}
          # Do not use credentials_json here for Workload Identity Federation

      - name: Authenticate to Google Cloud
        run: |
          gcloud auth login --brief --force
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_TEST_CREDENTIALS_WIF }}

      - name: Set up Workload Identity Federation
        run: |
          gcloud auth login --brief
          gcloud auth application-default login

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_TEST_PROJECT_ID }}/my-app:$GITHUB_SHA .

      - name: Push Docker image to Google Container Registry
        run: |
          docker push gcr.io/${{ secrets.GCP_TEST_PROJECT_ID }}/my-app:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-app \
            --image gcr.io/${{ secrets.GCP_TEST_PROJECT_ID }}/my-app:$GITHUB_SHA \
            --platform managed \
            --region ${{ secrets.GCP_TEST_REGION }} \
            --allow-unauthenticated

