name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Adjust to your main branch name

permissions:
  id-token: write  # Allows access to OIDC tokens
  contents: read   # Allows reading repository contents

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/1003608403675/locations/global/workloadIdentityPools/github-actions/providers/github-provider
          service_account: medical-admin-portal@unifycare-424906.iam.gserviceaccount.com

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_TEST_PROJECT_ID }}/my-node-app:$GITHUB_SHA .


      - name: Push Docker image
        run: |
          docker push gcr.io/${{ secrets.GCP_TEST_PROJECT_ID }}/my-node-app:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-node-app \
            --image gcr.io/${{ secrets.GCP_TEST_PROJECT_ID }}/my-node-app:$GITHUB_SHA \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated



