name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_TEST_PROJECT_ID }}

      - name: Authenticate to Google Cloud using Workload Identity Federation
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/1003608403675/locations/global/workloadIdentityPools/github-actions/providers/github-provider
          service_account: your-service-account@unifycare-424906.iam.gserviceaccount.com
  

      - name: Deploy to Google Cloud
        run: |
          gcloud app deploy


